### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by socathie** [bungun/pogs-python#1]
This is an error I get trying to import pogs. 
```
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pogs as pogs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/pogs/lib/python2.7/site-packages/pogs/__init__.py", line 4, in <module>
    from pogs.solvers.cpu import SolverCPU
  File "/home/ubuntu/anaconda3/envs/pogs/lib/python2.7/site-packages/pogs/solvers/__init__.py", line 1, in <module>
    from pogs.solvers.cpu import SolverCPU
  File "/home/ubuntu/anaconda3/envs/pogs/lib/python2.7/site-packages/pogs/solvers/cpu.py", line 1, in <module>
    from pogs.libs.cpu import pogsCPU
  File "/home/ubuntu/anaconda3/envs/pogs/lib/python2.7/site-packages/pogs/libs/cpu.py", line 9, in <module>
    lib_path=check_output(['locate', lib])
  File "/home/ubuntu/anaconda3/envs/pogs/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['locate', 'packages/libpogs.so']' returned non-zero exit status 1
```

**Comment by bungun** [comment]
hi cathie, may i recommend you try the much more up-to-date implementation of POGS with a well-tested python interface at https://github.com/bungun/optkit

update: it's been a bit since i've been able to update the optkit repo, but if you check the dev branch, there are usage examples https://github.com/bungun/optkit/tree/dev/examples
